### ISSUE TITLE
osm-libertyのアイコンセットを追加する

### ISSUE THREAD

**Issue by naogify** [geolonia/sprites.geolonia.com#9]
~~https://github.com/maputnik/osm-liberty/tree/gh-pages/svgs~~

https://github.com/maputnik/osm-liberty

**Comment by keichan34** [comment]
アイコンセットって [maki](https://github.com/mapbox/maki/blob/master/LICENSE.txt) 使ってるんじゃないですかね
(いまのって、maki ベースではなかったっけ。。)

**Comment by naogify** [comment]
あ、そうです…！osm-liberty のアイコンも Maki アイコンに互換性？があるので追加したいなと。

カラフルなアイコンで良さそうなので…！

https://github.com/maputnik/osm-liberty/blob/gh-pages/sprites/osm-liberty.png

**Comment by keichan34** [comment]
あ、いいね。特に国道・都道府県道・高速道路の標識を使いたいですね :)

**Comment by naogify** [comment]
良いですね! osm-libertyの道路標識がアメリカ？のものになっているので、日本の道路標識アイコンも追加したいです。

**Comment by naogify** [comment]
別のアイコンを混ぜるとライセンス確認が難しくなるので、自作するという方針で進める。
